// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pb/taskevents/taskevents.proto

package taskevents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskIDSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
}

func (x *TaskIDSet) Reset() {
	*x = TaskIDSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_taskevents_taskevents_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskIDSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskIDSet) ProtoMessage() {}

func (x *TaskIDSet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_taskevents_taskevents_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskIDSet.ProtoReflect.Descriptor instead.
func (*TaskIDSet) Descriptor() ([]byte, []int) {
	return file_pb_taskevents_taskevents_proto_rawDescGZIP(), []int{0}
}

func (x *TaskIDSet) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

type TaskQueueChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskQueue string `protobuf:"bytes,1,opt,name=TaskQueue,proto3" json:"TaskQueue,omitempty"`
}

func (x *TaskQueueChanged) Reset() {
	*x = TaskQueueChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_taskevents_taskevents_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskQueueChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQueueChanged) ProtoMessage() {}

func (x *TaskQueueChanged) ProtoReflect() protoreflect.Message {
	mi := &file_pb_taskevents_taskevents_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQueueChanged.ProtoReflect.Descriptor instead.
func (*TaskQueueChanged) Descriptor() ([]byte, []int) {
	return file_pb_taskevents_taskevents_proto_rawDescGZIP(), []int{1}
}

func (x *TaskQueueChanged) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

type StateChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State string `protobuf:"bytes,1,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *StateChanged) Reset() {
	*x = StateChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_taskevents_taskevents_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChanged) ProtoMessage() {}

func (x *StateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_pb_taskevents_taskevents_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChanged.ProtoReflect.Descriptor instead.
func (*StateChanged) Descriptor() ([]byte, []int) {
	return file_pb_taskevents_taskevents_proto_rawDescGZIP(), []int{2}
}

func (x *StateChanged) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type TimeoutChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeout int32 `protobuf:"varint,1,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
}

func (x *TimeoutChanged) Reset() {
	*x = TimeoutChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_taskevents_taskevents_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeoutChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutChanged) ProtoMessage() {}

func (x *TimeoutChanged) ProtoReflect() protoreflect.Message {
	mi := &file_pb_taskevents_taskevents_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutChanged.ProtoReflect.Descriptor instead.
func (*TimeoutChanged) Descriptor() ([]byte, []int) {
	return file_pb_taskevents_taskevents_proto_rawDescGZIP(), []int{3}
}

func (x *TimeoutChanged) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type MaxRetriesSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxRetries int32 `protobuf:"varint,1,opt,name=MaxRetries,proto3" json:"MaxRetries,omitempty"`
}

func (x *MaxRetriesSet) Reset() {
	*x = MaxRetriesSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_taskevents_taskevents_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxRetriesSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxRetriesSet) ProtoMessage() {}

func (x *MaxRetriesSet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_taskevents_taskevents_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxRetriesSet.ProtoReflect.Descriptor instead.
func (*MaxRetriesSet) Descriptor() ([]byte, []int) {
	return file_pb_taskevents_taskevents_proto_rawDescGZIP(), []int{4}
}

func (x *MaxRetriesSet) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type Created struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *Created) Reset() {
	*x = Created{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_taskevents_taskevents_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Created) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Created) ProtoMessage() {}

func (x *Created) ProtoReflect() protoreflect.Message {
	mi := &file_pb_taskevents_taskevents_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Created.ProtoReflect.Descriptor instead.
func (*Created) Descriptor() ([]byte, []int) {
	return file_pb_taskevents_taskevents_proto_rawDescGZIP(), []int{5}
}

func (x *Created) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Updated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *Updated) Reset() {
	*x = Updated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_taskevents_taskevents_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Updated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updated) ProtoMessage() {}

func (x *Updated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_taskevents_taskevents_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updated.ProtoReflect.Descriptor instead.
func (*Updated) Descriptor() ([]byte, []int) {
	return file_pb_taskevents_taskevents_proto_rawDescGZIP(), []int{6}
}

func (x *Updated) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Retried struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retries int32 `protobuf:"varint,1,opt,name=retries,proto3" json:"retries,omitempty"`
}

func (x *Retried) Reset() {
	*x = Retried{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_taskevents_taskevents_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Retried) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retried) ProtoMessage() {}

func (x *Retried) ProtoReflect() protoreflect.Message {
	mi := &file_pb_taskevents_taskevents_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retried.ProtoReflect.Descriptor instead.
func (*Retried) Descriptor() ([]byte, []int) {
	return file_pb_taskevents_taskevents_proto_rawDescGZIP(), []int{7}
}

func (x *Retried) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

var File_pb_taskevents_taskevents_proto protoreflect.FileDescriptor

var file_pb_taskevents_taskevents_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f,
	0x74, 0x61, 0x73, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x61, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x22, 0x23, 0x0a, 0x09, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x44, 0x53, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0x30,
	0x0a, 0x10, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x22, 0x24, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x2a, 0x0a, 0x0e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f,
	0x75, 0x74, 0x22, 0x2f, 0x0a, 0x0d, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x53, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x22, 0x27, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x27, 0x0a, 0x07,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x23, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x77, 0x6c, 0x69, 0x6e, 0x74, 0x2f,
	0x6d, 0x61, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_taskevents_taskevents_proto_rawDescOnce sync.Once
	file_pb_taskevents_taskevents_proto_rawDescData = file_pb_taskevents_taskevents_proto_rawDesc
)

func file_pb_taskevents_taskevents_proto_rawDescGZIP() []byte {
	file_pb_taskevents_taskevents_proto_rawDescOnce.Do(func() {
		file_pb_taskevents_taskevents_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_taskevents_taskevents_proto_rawDescData)
	})
	return file_pb_taskevents_taskevents_proto_rawDescData
}

var file_pb_taskevents_taskevents_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pb_taskevents_taskevents_proto_goTypes = []interface{}{
	(*TaskIDSet)(nil),        // 0: maestro.TaskIDSet
	(*TaskQueueChanged)(nil), // 1: maestro.TaskQueueChanged
	(*StateChanged)(nil),     // 2: maestro.StateChanged
	(*TimeoutChanged)(nil),   // 3: maestro.TimeoutChanged
	(*MaxRetriesSet)(nil),    // 4: maestro.MaxRetriesSet
	(*Created)(nil),          // 5: maestro.Created
	(*Updated)(nil),          // 6: maestro.Updated
	(*Retried)(nil),          // 7: maestro.Retried
}
var file_pb_taskevents_taskevents_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_taskevents_taskevents_proto_init() }
func file_pb_taskevents_taskevents_proto_init() {
	if File_pb_taskevents_taskevents_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_taskevents_taskevents_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskIDSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_taskevents_taskevents_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskQueueChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_taskevents_taskevents_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_taskevents_taskevents_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeoutChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_taskevents_taskevents_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxRetriesSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_taskevents_taskevents_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Created); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_taskevents_taskevents_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Updated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_taskevents_taskevents_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Retried); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_taskevents_taskevents_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_taskevents_taskevents_proto_goTypes,
		DependencyIndexes: file_pb_taskevents_taskevents_proto_depIdxs,
		MessageInfos:      file_pb_taskevents_taskevents_proto_msgTypes,
	}.Build()
	File_pb_taskevents_taskevents_proto = out.File
	file_pb_taskevents_taskevents_proto_rawDesc = nil
	file_pb_taskevents_taskevents_proto_goTypes = nil
	file_pb_taskevents_taskevents_proto_depIdxs = nil
}
