// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: pb/maestro.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueueName string `protobuf:"bytes,1,opt,name=queueName,proto3" json:"queueName,omitempty"`
}

func (x *QueueStatsRequest) Reset() {
	*x = QueueStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_maestro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsRequest) ProtoMessage() {}

func (x *QueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_maestro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsRequest.ProtoReflect.Descriptor instead.
func (*QueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_pb_maestro_proto_rawDescGZIP(), []int{0}
}

func (x *QueueStatsRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type QueueStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheduled []string `protobuf:"bytes,1,rep,name=scheduled,proto3" json:"scheduled,omitempty"`
	Pending   []string `protobuf:"bytes,2,rep,name=pending,proto3" json:"pending,omitempty"`
	Running   []string `protobuf:"bytes,3,rep,name=running,proto3" json:"running,omitempty"`
	Completed []string `protobuf:"bytes,4,rep,name=completed,proto3" json:"completed,omitempty"`
	Timedout  []string `protobuf:"bytes,5,rep,name=timedout,proto3" json:"timedout,omitempty"`
	Failed    []string `protobuf:"bytes,6,rep,name=failed,proto3" json:"failed,omitempty"`
}

func (x *QueueStatsResponse) Reset() {
	*x = QueueStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_maestro_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsResponse) ProtoMessage() {}

func (x *QueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_maestro_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsResponse.ProtoReflect.Descriptor instead.
func (*QueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_pb_maestro_proto_rawDescGZIP(), []int{1}
}

func (x *QueueStatsResponse) GetScheduled() []string {
	if x != nil {
		return x.Scheduled
	}
	return nil
}

func (x *QueueStatsResponse) GetPending() []string {
	if x != nil {
		return x.Pending
	}
	return nil
}

func (x *QueueStatsResponse) GetRunning() []string {
	if x != nil {
		return x.Running
	}
	return nil
}

func (x *QueueStatsResponse) GetCompleted() []string {
	if x != nil {
		return x.Completed
	}
	return nil
}

func (x *QueueStatsResponse) GetTimedout() []string {
	if x != nil {
		return x.Timedout
	}
	return nil
}

func (x *QueueStatsResponse) GetFailed() []string {
	if x != nil {
		return x.Failed
	}
	return nil
}

var File_pb_maestro_proto protoreflect.FileDescriptor

var file_pb_maestro_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x31, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x69, 0x6d, 0x65, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x69, 0x6d, 0x65, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x32, 0x49, 0x0a, 0x0e, 0x4d, 0x61, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x12, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x77, 0x6c, 0x69, 0x6e, 0x74,
	0x2f, 0x6d, 0x61, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_maestro_proto_rawDescOnce sync.Once
	file_pb_maestro_proto_rawDescData = file_pb_maestro_proto_rawDesc
)

func file_pb_maestro_proto_rawDescGZIP() []byte {
	file_pb_maestro_proto_rawDescOnce.Do(func() {
		file_pb_maestro_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_maestro_proto_rawDescData)
	})
	return file_pb_maestro_proto_rawDescData
}

var file_pb_maestro_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_maestro_proto_goTypes = []interface{}{
	(*QueueStatsRequest)(nil),  // 0: QueueStatsRequest
	(*QueueStatsResponse)(nil), // 1: QueueStatsResponse
}
var file_pb_maestro_proto_depIdxs = []int32{
	0, // 0: MaestroService.QueueStats:input_type -> QueueStatsRequest
	1, // 1: MaestroService.QueueStats:output_type -> QueueStatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_maestro_proto_init() }
func file_pb_maestro_proto_init() {
	if File_pb_maestro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_maestro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_maestro_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_maestro_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_maestro_proto_goTypes,
		DependencyIndexes: file_pb_maestro_proto_depIdxs,
		MessageInfos:      file_pb_maestro_proto_msgTypes,
	}.Build()
	File_pb_maestro_proto = out.File
	file_pb_maestro_proto_rawDesc = nil
	file_pb_maestro_proto_goTypes = nil
	file_pb_maestro_proto_depIdxs = nil
}
